#!/usr/bin/env node
// Regenerate src/naf.ts from the register itself.
//
// `recherche-entreprises` validates `activite_principale` against a closed list
// and, when the value is rejected, ANSWERS WITH THE WHOLE LIST. So the
// authoritative NAF rev.2 catalogue is one deliberately-invalid request away —
// no scraping an INSEE page, no hand-copied table that silently rots when the
// nomenclature is revised.
//
//   node scripts/refresh-naf.mjs        # rewrite src/naf.ts
//   node scripts/refresh-naf.mjs --check  # fail if the committed file is stale
//
// Why the codes are needed at all: the API caps any result set at 10 000 and
// accepts no prefix form of the filter ("62" is rejected, "62.01Z" is not). To
// get under the cap in a dense commune the SIRENE lane splits by NAF section,
// then by division — and a division filter can only be expressed as the list of
// every full code inside it.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "src", "naf.ts");
const check = process.argv.includes("--check");

const res = await fetch("https://recherche-entreprises.api.gouv.fr/search?activite_principale=__invalid__&per_page=1");
const body = await res.json();
const message = String(body?.erreur ?? "");
const codes = [...message.matchAll(/'(\d{2}\.\d{2}[A-Z])'/g)].map((m) => m[1]);

if (codes.length < 600) {
  console.error(`refresh-naf: the API returned ${codes.length} codes — expected ~730. Did the error format change?`);
  console.error(`  message was: ${message.slice(0, 200)}`);
  process.exit(1);
}

// NAF section boundaries, by 2-digit division. This mapping is part of the
// nomenclature's definition rather than of the data, so it is stated here.
const SECTIONS = [
  ["A", 1, 3],
  ["B", 5, 9],
  ["C", 10, 33],
  ["D", 35, 35],
  ["E", 36, 39],
  ["F", 41, 43],
  ["G", 45, 47],
  ["H", 49, 53],
  ["I", 55, 56],
  ["J", 58, 63],
  ["K", 64, 66],
  ["L", 68, 68],
  ["M", 69, 75],
  ["N", 77, 82],
  ["O", 84, 84],
  ["P", 85, 85],
  ["Q", 86, 88],
  ["R", 90, 93],
  ["S", 94, 96],
  ["T", 97, 98],
  ["U", 99, 99],
];

const unmapped = codes.filter((c) => {
  const div = Number.parseInt(c.slice(0, 2), 10);
  return !SECTIONS.some(([, lo, hi]) => div >= lo && div <= hi);
});
if (unmapped.length) {
  console.error(`refresh-naf: ${unmapped.length} code(s) fall outside every known section: ${unmapped.slice(0, 10).join(", ")}`);
  process.exit(1);
}

const generated = `// GENERATED by scripts/refresh-naf.mjs — do not edit by hand.
//
// The NAF rev.2 activity catalogue, read from the register's own validation
// error (it answers a rejected \`activite_principale\` with the complete list of
// valid ones). Regenerate with \`node scripts/refresh-naf.mjs\`; CI runs
// \`--check\` so a nomenclature revision shows up as a failed build rather than
// as a partition that silently stops covering part of the economy.
//
// ${codes.length} codes across ${SECTIONS.length} sections, as of the last refresh.

/** Section letter -> inclusive range of 2-digit NAF divisions. */
export const NAF_SECTION_DIVISIONS: ReadonlyArray<readonly [string, number, number]> = [
${SECTIONS.map(([s, lo, hi]) => `  ["${s}", ${lo}, ${hi}],`).join("\n")}
];

/** Every valid \`activite_principale\` value, in nomenclature order. */
export const NAF_CODES: readonly string[] = [
${chunk(codes, 8)
  .map((row) => "  " + row.map((c) => `"${c}"`).join(", ") + ",")
  .join("\n")}
];

/** The section letter a full NAF code belongs to, or undefined if malformed. */
export function nafSection(code: string): string | undefined {
  const div = Number.parseInt(code.slice(0, 2), 10);
  if (!Number.isFinite(div)) return undefined;
  return NAF_SECTION_DIVISIONS.find(([, lo, hi]) => div >= lo && div <= hi)?.[0];
}

/** Every NAF code in a section, grouped by 2-digit division. */
export function divisionsOfSection(section: string): string[][] {
  const byDivision = new Map<string, string[]>();
  for (const code of NAF_CODES) {
    if (nafSection(code) !== section) continue;
    const div = code.slice(0, 2);
    const list = byDivision.get(div);
    if (list) list.push(code);
    else byDivision.set(div, [code]);
  }
  return [...byDivision.values()];
}

/** All section letters, in nomenclature order. */
export const NAF_SECTIONS: readonly string[] = NAF_SECTION_DIVISIONS.map(([s]) => s);
`;

function chunk(items, size) {
  const rows = [];
  for (let i = 0; i < items.length; i += size) rows.push(items.slice(i, i + size));
  return rows;
}

if (check) {
  let current = "";
  try {
    current = readFileSync(out, "utf8");
  } catch {}
  if (current !== generated) {
    console.error("refresh-naf: src/naf.ts is stale — run `node scripts/refresh-naf.mjs` and commit the result.");
    process.exit(1);
  }
  console.log(`refresh-naf: src/naf.ts is current (${codes.length} codes).`);
  process.exit(0);
}

writeFileSync(out, generated);
console.log(`refresh-naf: wrote src/naf.ts with ${codes.length} NAF codes across ${SECTIONS.length} sections.`);
