#!/usr/bin/env node
// Regenerate src/classification/naf-codes.ts from the register itself.
//
// `recherche-entreprises` validates `activite_principale` against a closed list
// and, when the value is rejected, ANSWERS WITH THE WHOLE LIST. So the
// authoritative NAF rev.2 catalogue is one deliberately-invalid request away —
// no scraping an INSEE page, no hand-copied table that silently rots when the
// nomenclature is revised.
//
//   node scripts/refresh-naf.mjs          # rewrite the catalogue
//   node scripts/refresh-naf.mjs --check  # fail if the committed file is stale
//
// Why the codes are needed at all: the API caps any result set at 10 000 and
// accepts no prefix form of the filter ("62" is rejected, "62.01Z" is not). To
// get under the cap in a dense commune the French connector splits by NACE
// section, then by division — and a division filter can only be expressed as the
// list of every full code inside it.
//
// This is A FRENCH WORKAROUND, not a taxonomy requirement, and it is deliberately
// NOT replicated per country: every other register in this tool has its own cap
// and its own filter grammar, and most have no bulk enumeration at all.
//
// The section boundaries this used to emit now live in
// src/classification/nace.ts, hand-written: they are NACE rev.2 and shared with
// the German, Spanish and British connectors, so a French code generator has no
// business owning them. The SECTIONS table below is kept only to validate that
// every harvested code lands inside a known section.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "src", "classification", "naf-codes.ts");
const check = process.argv.includes("--check");

const res = await fetch("https://recherche-entreprises.api.gouv.fr/search?activite_principale=__invalid__&per_page=1");
const body = await res.json();
const message = String(body?.erreur ?? "");
const codes = [...message.matchAll(/'(\d{2}\.\d{2}[A-Z])'/g)].map((m) => m[1]);

if (codes.length < 600) {
  console.error(`refresh-naf: the API returned ${codes.length} codes — expected ~730. Did the error format change?`);
  console.error(`  message was: ${message.slice(0, 200)}`);
  process.exit(1);
}

// NACE section boundaries, by 2-digit division. Mirrors NACE_SECTION_DIVISIONS
// in src/classification/nace.ts and is used ONLY to reject a harvested code that
// falls outside every known section — the emitted file no longer carries them.
const SECTIONS = [
  ["A", 1, 3],
  ["B", 5, 9],
  ["C", 10, 33],
  ["D", 35, 35],
  ["E", 36, 39],
  ["F", 41, 43],
  ["G", 45, 47],
  ["H", 49, 53],
  ["I", 55, 56],
  ["J", 58, 63],
  ["K", 64, 66],
  ["L", 68, 68],
  ["M", 69, 75],
  ["N", 77, 82],
  ["O", 84, 84],
  ["P", 85, 85],
  ["Q", 86, 88],
  ["R", 90, 93],
  ["S", 94, 96],
  ["T", 97, 98],
  ["U", 99, 99],
];

const unmapped = codes.filter((c) => {
  const div = Number.parseInt(c.slice(0, 2), 10);
  return !SECTIONS.some(([, lo, hi]) => div >= lo && div <= hi);
});
if (unmapped.length) {
  console.error(`refresh-naf: ${unmapped.length} code(s) fall outside every known section: ${unmapped.slice(0, 10).join(", ")}`);
  process.exit(1);
}

const generated = `// GENERATED by scripts/refresh-naf.mjs — do not edit by hand.
//
// Excluded from biome in biome.json: the formatter rewrote this file's array
// layout, after which \`--check\` compared the generator's output against a
// reformatted file and could never pass again. A generated file has one owner.
//
// The NAF rev.2 code catalogue, read from the register's own validation error
// (it answers a rejected \`activite_principale\` with the complete list of valid
// ones). Regenerate with \`node scripts/refresh-naf.mjs\`. The weekly upstream
// canary runs \`--check\`, so a nomenclature revision surfaces as a drift report
// rather than as a partition that silently stops covering part of the economy.
// It is NOT a build gate: it depends on a third-party API being up, and a code
// gate that goes red for somebody else's outage is a gate people learn to
// ignore.
//
// FRANCE ONLY. The section structure these codes hang off is NACE rev.2 and
// lives in ./nace.ts, shared with the German, Spanish and British connectors.
// What is French here is the exhaustive code list, and it exists solely because
// the French API caps a result set at 10 000 and refuses a prefix filter.
//
// ${codes.length} codes across ${SECTIONS.length} sections, as of the last refresh.
import { naceSection } from "./nace.js";

/** Every valid \`activite_principale\` value, in nomenclature order. */
export const NAF_CODES: readonly string[] = [
${chunk(codes, 8)
  .map((row) => "  " + row.map((c) => `"${c}"`).join(", ") + ",")
  .join("\n")}
];

/** Every NAF code in a NACE section, grouped by 2-digit division. */
export function divisionsOfSection(section: string): string[][] {
  const byDivision = new Map<string, string[]>();
  for (const code of NAF_CODES) {
    if (naceSection(code) !== section) continue;
    const div = code.slice(0, 2);
    const list = byDivision.get(div);
    if (list) list.push(code);
    else byDivision.set(div, [code]);
  }
  return [...byDivision.values()];
}
`;

function chunk(items, size) {
  const rows = [];
  for (let i = 0; i < items.length; i += size) rows.push(items.slice(i, i + size));
  return rows;
}

if (check) {
  let current = "";
  try {
    current = readFileSync(out, "utf8");
  } catch {}
  if (current !== generated) {
    console.error("refresh-naf: src/classification/naf-codes.ts is stale — run `node scripts/refresh-naf.mjs` and commit the result.");
    process.exit(1);
  }
  console.log(`refresh-naf: src/classification/naf-codes.ts is current (${codes.length} codes).`);
  process.exit(0);
}

writeFileSync(out, generated);
console.log(`refresh-naf: wrote src/classification/naf-codes.ts with ${codes.length} NAF codes across ${SECTIONS.length} sections.`);
